Fix past deliveries accordions
OpenOlitor/openolitor-client-kundenportal pull request #103
Opened 2020-10-05 16:57 UTC by immora

Before: 
![initial_bug](https://user-images.githubusercontent.com/1473321/95108913-2a0f2580-073c-11eb-8a8c-8cb08de077bc.gif)

After:
![fixed_bug](https://user-images.githubusercontent.com/1473321/95109182-883c0880-073c-11eb-8ba2-a0a2717d5458.gif)

2020-10-12 15:21 UTC, mcmpp commented
Hi @immora , thanks so much for your contribution. 
There is only one missing thing. For the version, we have the bumpversion.sh script that upgrade the version in all files that is needed. Please, if you run it and push the result I accept this pull request.

2020-10-12 18:37 UTC, immora commented
> Hi @immora , thanks so much for your contribution.
> There is only one missing thing. For the version, we have the bumpversion.sh script that upgrade the version in all files that is needed. Please, if you run it and push the result I accept this pull request.

Hello @mcmpp! Done :) Although I'm not sure if the version is totally correct, as there exists tag with 2.4.0.... But I used the bash script like you wrote.

LG,
Kasia

2020-10-12 18:44 UTC, mcmpp commented
@immora , thanks so much. I will approve and close. As you already know the project and use it, do not hesitate to report other bugs, fix them, helping out with translations or any other task that you could think is helpful. 
A good way to start, if you haven't already read it is https://github.com/OpenOlitor/OpenOlitor/blob/prod/CONTRIBUTING.md

Have a great evening

2020-10-12 18:45 UTC, mcmpp approved these changes

2020-10-12 20:42 UTC, mcmpp requested changes

2020-10-12 20:42 UTC, mcmpp commented on variables.json
> +            "m1": "http://localhost:8080/api-csa1/"
Sorry, I have accepted it before seeing this issue. This file should not be modified

2020-10-13 19:26 UTC, immora commented on variables.json
> +            "m1": "http://localhost:8080/api-csa1/"
Reverted and version bumped again after pulling new prod branch

2020-10-14 07:52 UTC, mcmpp approved these changes

2020-10-14 07:52 UTC, merged